# Generated by Django 5.0.14 on 2025-10-14 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id_campo', models.UUIDField(db_column='id_campo', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=20)),
                ('clase', models.CharField(db_column='clase', max_length=30)),
                ('nombre_campo', models.CharField(db_column='nombre_campo', max_length=64)),
                ('etiqueta', models.CharField(db_column='etiqueta', max_length=100)),
                ('ayuda', models.CharField(blank=True, db_column='ayuda', max_length=255, null=True)),
                ('config', models.TextField(blank=True, db_column='config', null=True)),
                ('requerido', models.BooleanField(db_column='requerido', null=True)),
            ],
            options={
                'db_table': 'formularios_campo',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'formularios_categoria',
            },
        ),
        migrations.CreateModel(
            name='ClaseCampo',
            fields=[
                ('clase', models.CharField(db_column='clase', max_length=30, primary_key=True, serialize=False)),
                ('estructura', models.TextField(blank=True, db_column='estructura', null=True)),
            ],
            options={
                'db_table': 'formularios_clase_campo',
            },
        ),
        migrations.CreateModel(
            name='PaginaVersion',
            fields=[
                ('id_pagina_version', models.CharField(db_column='id_pagina_version', max_length=32, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(db_column='fecha_creacion')),
                ('id_pagina', models.CharField(db_column='id_pagina', max_length=32, null=True)),
            ],
            options={
                'db_table': 'formularios_pagina_version',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_usuario', models.CharField(db_column='nombre_usuario', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('acceso_web', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='formularios_usuarios', related_query_name='formularios_usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='formularios_usuarios', related_query_name='formularios_usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'formularios_usuario',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('permitir_fotos', models.BooleanField(default=False)),
                ('permitir_gps', models.BooleanField(default=False)),
                ('disponible_desde_fecha', models.DateField()),
                ('disponible_hasta_fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Ingresada', 'Ingresada'), ('Activa', 'Activa'), ('Suspendida', 'Suspendida'), ('Pruebas', 'Pruebas'), ('Anulada', 'Anulada')], max_length=20)),
                ('forma_envio', models.CharField(choices=[('En Linea/fuera Linea', 'En Linea/fuera Linea'), ('En Linea', 'En Linea'), ('Guardar', 'Guardar')], max_length=30)),
                ('es_publico', models.BooleanField(default=False)),
                ('auto_envio', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.categoria')),
            ],
            options={
                'db_table': 'formularios_formulario',
            },
        ),
        migrations.CreateModel(
            name='FormularioIndexVersion',
            fields=[
                ('id_index_version', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('formulario_id', models.ForeignKey(db_column='formulario_id', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='formularios.formulario')),
            ],
            options={
                'db_table': 'formularios_formularioindexversion',
            },
        ),
        migrations.CreateModel(
            name='FuenteDatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('blob_name', models.CharField(max_length=500)),
                ('blob_url', models.URLField(max_length=1000)),
                ('tipo_archivo', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('columnas', models.JSONField(default=list)),
                ('preview_data', models.JSONField(default=list)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_datos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formularios_fuente_datos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.UUIDField(db_column='id_grupo', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('id_campo_group', models.OneToOneField(db_column='id_campo_group', on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='formularios.campo')),
            ],
            options={
                'db_table': 'formularios_grupo',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id_pagina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('formulario_id', models.ForeignKey(db_column='formulario_id', on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='formularios.formulario')),
                ('index_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='formularios.formularioindexversion')),
            ],
            options={
                'db_table': 'formularios_pagina',
                'ordering': ['secuencia'],
            },
        ),
        migrations.CreateModel(
            name='Formulario_Index_Version',
            fields=[
                ('id_index_version', models.OneToOneField(db_column='id_index_version', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='row_historial', serialize=False, to='formularios.formularioindexversion')),
                ('id_formulario', models.ForeignKey(db_column='id_formulario', on_delete=django.db.models.deletion.CASCADE, related_name='versiones_hist', to='formularios.formulario')),
            ],
            options={
                'db_table': 'formularios_formularios_index_version',
            },
        ),
        migrations.CreateModel(
            name='FuenteDatosValor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('columna', models.CharField(blank=True, default='', max_length=200)),
                ('key_text', models.TextField(blank=True, null=True)),
                ('label_text', models.TextField()),
                ('valor_raw', models.JSONField(default=dict)),
                ('extras', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_vals', to='formularios.campo')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.fuentedatos')),
            ],
            options={
                'db_table': 'formularios_fuente_datos_valor',
                'indexes': [models.Index(fields=['campo', 'label_text'], name='formularios_campo_i_254189_idx'), models.Index(fields=['campo', 'key_text'], name='formularios_campo_i_4d9317_idx')],
                'unique_together': {('campo', 'key_text')},
            },
        ),
        migrations.CreateModel(
            name='CampoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campo', models.ForeignKey(db_column='id_campo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='formularios.campo')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='formularios.grupo')),
            ],
            options={
                'db_table': 'formularios_campo_grupo',
                'unique_together': {('id_grupo', 'id_campo')},
            },
        ),
        migrations.CreateModel(
            name='Pagina_Index_Version',
            fields=[
                ('id_pagina', models.OneToOneField(db_column='id_pagina', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='puntero_version', serialize=False, to='formularios.pagina')),
                ('id_index_version', models.ForeignKey(db_column='id_index_version', on_delete=django.db.models.deletion.CASCADE, related_name='paginas_puntero', to='formularios.formularioindexversion')),
            ],
            options={
                'db_table': 'formularios_pagina_index_version',
            },
        ),
        migrations.CreateModel(
            name='UserFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.formulario')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formularios_user_formulario',
                'indexes': [models.Index(fields=['id_usuario', 'id_formulario'], name='formularios_id_usua_73941f_idx')],
                'unique_together': {('id_formulario', 'id_usuario')},
            },
        ),
        migrations.CreateModel(
            name='PaginaCampo',
            fields=[
                ('id_campo', models.ForeignKey(db_column='id_campo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enlaces_pagina', serialize=False, to='formularios.campo')),
                ('sequence', models.PositiveIntegerField(db_column='sequence', null=True)),
                ('id_pagina_version', models.ForeignKey(db_column='id_pagina_version', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formularios.paginaversion')),
            ],
            options={
                'db_table': 'formularios_pagina_campo',
                'unique_together': {('id_campo', 'id_pagina_version')},
            },
        ),
    ]
