# Generated by Django 5.0.14 on 2025-10-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "id_usuario",
                    models.CharField(
                        blank=True, db_column="id_usuario_id", max_length=150, null=True
                    ),
                ),
                ("form_id", models.UUIDField(db_column="form_id")),
                ("index_version_id", models.UUIDField(db_column="index_version_id")),
                ("form_name", models.CharField(db_column="form_name", max_length=200)),
                (
                    "filled_at_local",
                    models.DateTimeField(
                        blank=True, db_column="filled_at_local", null=True
                    ),
                ),
                ("status", models.CharField(db_column="status", max_length=50)),
                (
                    "fill_json",
                    models.JSONField(blank=True, db_column="fill_json", null=True),
                ),
                (
                    "form_json",
                    models.JSONField(blank=True, db_column="form_json", null=True),
                ),
                ("created_at", models.DateTimeField(db_column="created_at")),
                ("updated_at", models.DateTimeField(db_column="updated_at")),
            ],
            options={
                "db_table": "formularios_entry",
                "ordering": ("-created_at",),
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="formulario",
            name="periodicidad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Ingresado", "Ingresado"),
                    ("Activo", "Activo"),
                    ("Suspendido", "Suspendido"),
                    ("Pruebas", "Pruebas"),
                    ("Anulado", "Anulado"),
                ],
                max_length=20,
            ),
        ),
    ]
