# Generated by Django 5.0.14 on 2025-10-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0002_formularioentry_formulario_periodicidad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paginaversion",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.AlterField(
            model_name="paginaversion",
            name="id_pagina",
            field=models.ForeignKey(
                db_column="id_pagina",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versiones_pagina",
                to="formularios.pagina",
            ),
        ),
    ]
