# Generated by Django 5.0.14 on 2025-10-22 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0003_alter_paginaversion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paginaversion",
            name="index_version",
            field=models.ForeignKey(
                blank=True,
                db_column="index_version_id",
                help_text="Versión del formulario a la que pertenece esta versión de página",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paginas_versiones",
                to="formularios.formularioindexversion",
            ),
        ),
    ]
