# Generated by Django 5.0.14 on 2025-10-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0004_paginaversion_index_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paginaversion",
            index=models.Index(
                fields=["id_pagina", "-fecha_creacion"],
                name="formularios_id_pagi_78e8b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paginaversion",
            index=models.Index(
                fields=["index_version", "-fecha_creacion"],
                name="formularios_index_v_1e54e0_idx",
            ),
        ),
    ]
