# Generated by Django 5.0.14 on 2025-10-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0005_paginaversion_formularios_id_pagi_78e8b2_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 1) Índice en paginaversion (no fallar si ya no existe)
                migrations.RunSQL(
                    """
                    DROP INDEX IF EXISTS formularios_index_v_1e54e0_idx;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # 2) Columnas eliminadas manualmente (no fallar si ya no existen)
                migrations.RunSQL(
                    """
                    ALTER TABLE formularios_formularioindexversion
                    DROP COLUMN IF EXISTS formulario_id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE formularios_pagina
                    DROP COLUMN IF EXISTS formulario_id,
                    DROP COLUMN IF EXISTS index_version_id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE formularios_pagina_version
                    DROP COLUMN IF EXISTS index_version_id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # Reflejar en el estado de migraciones lo que ya hiciste en BD
                migrations.RemoveIndex(
                    model_name="paginaversion",
                    name="formularios_index_v_1e54e0_idx",
                ),
                migrations.RemoveField(
                    model_name="formularioindexversion",
                    name="formulario_id",
                ),
                migrations.RemoveField(
                    model_name="pagina",
                    name="formulario_id",
                ),
                migrations.RemoveField(
                    model_name="pagina",
                    name="index_version",
                ),
                migrations.RemoveField(
                    model_name="paginaversion",
                    name="index_version",
                ),
            ],
        ),
    ]
